version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ewa-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend/cache:/app/cache
      - ./backend:/app
    networks:
      - ewa-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health', timeout=10)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ewa-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - ewa-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  # Optional: Redis for enhanced caching (can be added later)
  # redis:
  #   image: redis:7-alpine
  #   container_name: ewa-redis
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - ewa-network
  #   command: redis-server --appendonly yes
  #   volumes:
  #     - redis-data:/data

networks:
  ewa-network:
    driver: bridge

volumes:
  backend-cache:
    driver: local
  # redis-data:
  #   driver: local